#!/bin/sh
#
# Upgrade factory snapshot on device
# Copyright (C) 2015 Jolla Ltd.
# Contact: Thomas Perl <thomas.perl@jolla.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#


SFMF_DEPLOY="/usr/bin/sfmf-deploy"

FACTORY_NAME="factory"
FACTORY_RENAME="factory-old"
SNAPSHOT_NAME="factory-slipstream-tmp"

echo "Deploying snapshot..."
set -e
set -x
sailfish-snapshot list
sailfish-snapshot delete "$SNAPSHOT_NAME" || true
sailfish-snapshot deploy "$SFMF_DEPLOY" "$SNAPSHOT_NAME"
sailfish-snapshot delete "$FACTORY_RENAME" || true
sailfish-snapshot rename "$FACTORY_NAME" "$FACTORY_RENAME"
sailfish-snapshot rename "$SNAPSHOT_NAME" "$FACTORY_NAME"
sailfish-snapshot list
set +x
# TODO: Cleanup "$FACTORY_RENAME"?
echo "Done."
